[package]
name = "LicenSeed"
version = "0.0.0"
description = "A Tauri App"
authors = ["wappon28dev"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc", features = [] }
tauri-plugin-shell = "2.0.0-rc"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

###

specta = { version = "2.0.0-rc.20" }
specta-typescript = { version = "0.0.7" }
tauri-specta = { version = "2.0.0-rc.12", features = ["derive", "typescript"] }
specta-jsdoc = { version = "0.0.7" }
